cc_library(
    name = "tuple",
    hdrs = glob(["inc/*"]),
    visibility = [
        "//utils/jit:__pkg__",
    ],
    includes = [
        "inc",
    ],
    deps = [
        "//utils/array:array"
    ]
)
