cc_library(
    name = "tuple",
    hdrs = glob(["inc/*"]),
    visibility = [
        "//visibility:public"
    ],
    includes = [
        "inc",
    ],
    deps = [
        "//utils/array:array"
    ]
)
