cc_library(
    name = "dl",
    srcs = glob(["src/dl.cpp"]),
    hdrs = glob(["inc/dl.hpp"]),
    visibility = ["//src:__pkg__"],
    includes = ["inc"],
    deps = [
        "//utils/jit:jit",
    ]
)

