cc_library(
    name = "dl",
    srcs = glob(["src/dl.cpp"]),
    hdrs = glob(["inc/dl.hpp"]),
    visibility = ["//src:__pkg__"],
    includes = ["inc"]
    # copts = ["-Iinc"]
)

cc_library(
    name = "dl_hdr",
    srcs = glob(["inc/dl.cpp"]),
    visibility = ["//src:__pkg__"],
)