cc_library(
    name = "fnv1a",
    hdrs = glob(["inc/*"]),
    visibility = [
        "//utils/jit:__pkg__"
    ],
    deps = [
        "//utils/string:string",
    ],
    includes = [
        "inc",
    ],
)
