cc_library(
    name = "traits",
    hdrs = glob(["inc/*"]),
    visibility = [
        "//src:__pkg__",
        "//utils/env:__pkg__",
        # "@openssl//:openssl",
    ],
    includes = ["inc"],
    copts = [
            "-Iinc/",
    ],
)

