cc_library(
    name = "sha256",
    srcs = glob(["*.hpp", "*.cpp"]),
    hdrs = glob(["hpp"]),
    visibility = [
        "//utils/env:__pkg__",
        "//utils/jit:__pkg__"
    ],
    includes = [
        "./",
    ],
)
