// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: env_info.proto

#ifndef PROTOBUF_INCLUDED_env_5finfo_2eproto
#define PROTOBUF_INCLUDED_env_5finfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_env_5finfo_2eproto 

namespace protobuf_env_5finfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_env_5finfo_2eproto
class env_config_header_t;
class env_config_header_tDefaultTypeInternal;
extern env_config_header_tDefaultTypeInternal _env_config_header_t_default_instance_;
class env_config_t;
class env_config_tDefaultTypeInternal;
extern env_config_tDefaultTypeInternal _env_config_t_default_instance_;
namespace google {
namespace protobuf {
template<> ::env_config_header_t* Arena::CreateMaybeMessage<::env_config_header_t>(Arena*);
template<> ::env_config_t* Arena::CreateMaybeMessage<::env_config_t>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class env_config_header_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:env_config_header_t) */ {
 public:
  env_config_header_t();
  virtual ~env_config_header_t();

  env_config_header_t(const env_config_header_t& from);

  inline env_config_header_t& operator=(const env_config_header_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  env_config_header_t(env_config_header_t&& from) noexcept
    : env_config_header_t() {
    *this = ::std::move(from);
  }

  inline env_config_header_t& operator=(env_config_header_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const env_config_header_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const env_config_header_t* internal_default_instance() {
    return reinterpret_cast<const env_config_header_t*>(
               &_env_config_header_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(env_config_header_t* other);
  friend void swap(env_config_header_t& a, env_config_header_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline env_config_header_t* New() const final {
    return CreateMaybeMessage<env_config_header_t>(NULL);
  }

  env_config_header_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<env_config_header_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const env_config_header_t& from);
  void MergeFrom(const env_config_header_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(env_config_header_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes env_name = 1 [default = ""];
  bool has_env_name() const;
  void clear_env_name();
  static const int kEnvNameFieldNumber = 1;
  const ::std::string& env_name() const;
  void set_env_name(const ::std::string& value);
  #if LANG_CXX11
  void set_env_name(::std::string&& value);
  #endif
  void set_env_name(const char* value);
  void set_env_name(const void* value, size_t size);
  ::std::string* mutable_env_name();
  ::std::string* release_env_name();
  void set_allocated_env_name(::std::string* env_name);

  // required bytes env_host_name = 5 [default = ""];
  bool has_env_host_name() const;
  void clear_env_host_name();
  static const int kEnvHostNameFieldNumber = 5;
  const ::std::string& env_host_name() const;
  void set_env_host_name(const ::std::string& value);
  #if LANG_CXX11
  void set_env_host_name(::std::string&& value);
  #endif
  void set_env_host_name(const char* value);
  void set_env_host_name(const void* value, size_t size);
  ::std::string* mutable_env_host_name();
  ::std::string* release_env_host_name();
  void set_allocated_env_host_name(::std::string* env_host_name);

  // required bytes env_invite = 6 [default = ""];
  bool has_env_invite() const;
  void clear_env_invite();
  static const int kEnvInviteFieldNumber = 6;
  const ::std::string& env_invite() const;
  void set_env_invite(const ::std::string& value);
  #if LANG_CXX11
  void set_env_invite(::std::string&& value);
  #endif
  void set_env_invite(const char* value);
  void set_env_invite(const void* value, size_t size);
  ::std::string* mutable_env_invite();
  ::std::string* release_env_invite();
  void set_allocated_env_invite(::std::string* env_invite);

  // required int32 env_ipv4_stream_port = 2 [default = 0];
  bool has_env_ipv4_stream_port() const;
  void clear_env_ipv4_stream_port();
  static const int kEnvIpv4StreamPortFieldNumber = 2;
  ::google::protobuf::int32 env_ipv4_stream_port() const;
  void set_env_ipv4_stream_port(::google::protobuf::int32 value);

  // required int32 env_ipv6_stream_port = 3 [default = 0];
  bool has_env_ipv6_stream_port() const;
  void clear_env_ipv6_stream_port();
  static const int kEnvIpv6StreamPortFieldNumber = 3;
  ::google::protobuf::int32 env_ipv6_stream_port() const;
  void set_env_ipv6_stream_port(::google::protobuf::int32 value);

  // required int32 env_pid = 4 [default = 0];
  bool has_env_pid() const;
  void clear_env_pid();
  static const int kEnvPidFieldNumber = 4;
  ::google::protobuf::int32 env_pid() const;
  void set_env_pid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:env_config_header_t)
 private:
  void set_has_env_name();
  void clear_has_env_name();
  void set_has_env_ipv4_stream_port();
  void clear_has_env_ipv4_stream_port();
  void set_has_env_ipv6_stream_port();
  void clear_has_env_ipv6_stream_port();
  void set_has_env_pid();
  void clear_has_env_pid();
  void set_has_env_host_name();
  void clear_has_env_host_name();
  void set_has_env_invite();
  void clear_has_env_invite();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr env_name_;
  ::google::protobuf::internal::ArenaStringPtr env_host_name_;
  ::google::protobuf::internal::ArenaStringPtr env_invite_;
  ::google::protobuf::int32 env_ipv4_stream_port_;
  ::google::protobuf::int32 env_ipv6_stream_port_;
  ::google::protobuf::int32 env_pid_;
  friend struct ::protobuf_env_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class env_config_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:env_config_t) */ {
 public:
  env_config_t();
  virtual ~env_config_t();

  env_config_t(const env_config_t& from);

  inline env_config_t& operator=(const env_config_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  env_config_t(env_config_t&& from) noexcept
    : env_config_t() {
    *this = ::std::move(from);
  }

  inline env_config_t& operator=(env_config_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const env_config_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const env_config_t* internal_default_instance() {
    return reinterpret_cast<const env_config_t*>(
               &_env_config_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(env_config_t* other);
  friend void swap(env_config_t& a, env_config_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline env_config_t* New() const final {
    return CreateMaybeMessage<env_config_t>(NULL);
  }

  env_config_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<env_config_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const env_config_t& from);
  void MergeFrom(const env_config_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(env_config_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes env_name = 1 [default = ""];
  bool has_env_name() const;
  void clear_env_name();
  static const int kEnvNameFieldNumber = 1;
  const ::std::string& env_name() const;
  void set_env_name(const ::std::string& value);
  #if LANG_CXX11
  void set_env_name(::std::string&& value);
  #endif
  void set_env_name(const char* value);
  void set_env_name(const void* value, size_t size);
  ::std::string* mutable_env_name();
  ::std::string* release_env_name();
  void set_allocated_env_name(::std::string* env_name);

  // required bytes env_headers_path = 2 [default = ""];
  bool has_env_headers_path() const;
  void clear_env_headers_path();
  static const int kEnvHeadersPathFieldNumber = 2;
  const ::std::string& env_headers_path() const;
  void set_env_headers_path(const ::std::string& value);
  #if LANG_CXX11
  void set_env_headers_path(::std::string&& value);
  #endif
  void set_env_headers_path(const char* value);
  void set_env_headers_path(const void* value, size_t size);
  ::std::string* mutable_env_headers_path();
  ::std::string* release_env_headers_path();
  void set_allocated_env_headers_path(::std::string* env_headers_path);

  // required bytes env_mountpoint = 3 [default = ""];
  bool has_env_mountpoint() const;
  void clear_env_mountpoint();
  static const int kEnvMountpointFieldNumber = 3;
  const ::std::string& env_mountpoint() const;
  void set_env_mountpoint(const ::std::string& value);
  #if LANG_CXX11
  void set_env_mountpoint(::std::string&& value);
  #endif
  void set_env_mountpoint(const char* value);
  void set_env_mountpoint(const void* value, size_t size);
  ::std::string* mutable_env_mountpoint();
  ::std::string* release_env_mountpoint();
  void set_allocated_env_mountpoint(::std::string* env_mountpoint);

  // required bytes env_components_path = 4 [default = ""];
  bool has_env_components_path() const;
  void clear_env_components_path();
  static const int kEnvComponentsPathFieldNumber = 4;
  const ::std::string& env_components_path() const;
  void set_env_components_path(const ::std::string& value);
  #if LANG_CXX11
  void set_env_components_path(::std::string&& value);
  #endif
  void set_env_components_path(const char* value);
  void set_env_components_path(const void* value, size_t size);
  ::std::string* mutable_env_components_path();
  ::std::string* release_env_components_path();
  void set_allocated_env_components_path(::std::string* env_components_path);

  // required bytes env_x509_certificate_path = 5 [default = ""];
  bool has_env_x509_certificate_path() const;
  void clear_env_x509_certificate_path();
  static const int kEnvX509CertificatePathFieldNumber = 5;
  const ::std::string& env_x509_certificate_path() const;
  void set_env_x509_certificate_path(const ::std::string& value);
  #if LANG_CXX11
  void set_env_x509_certificate_path(::std::string&& value);
  #endif
  void set_env_x509_certificate_path(const char* value);
  void set_env_x509_certificate_path(const void* value, size_t size);
  ::std::string* mutable_env_x509_certificate_path();
  ::std::string* release_env_x509_certificate_path();
  void set_allocated_env_x509_certificate_path(::std::string* env_x509_certificate_path);

  // required bytes env_network_ifname = 6 [default = ""];
  bool has_env_network_ifname() const;
  void clear_env_network_ifname();
  static const int kEnvNetworkIfnameFieldNumber = 6;
  const ::std::string& env_network_ifname() const;
  void set_env_network_ifname(const ::std::string& value);
  #if LANG_CXX11
  void set_env_network_ifname(::std::string&& value);
  #endif
  void set_env_network_ifname(const char* value);
  void set_env_network_ifname(const void* value, size_t size);
  ::std::string* mutable_env_network_ifname();
  ::std::string* release_env_network_ifname();
  void set_allocated_env_network_ifname(::std::string* env_network_ifname);

  // required bytes env_ipv4_multicast_group_addr = 7 [default = ""];
  bool has_env_ipv4_multicast_group_addr() const;
  void clear_env_ipv4_multicast_group_addr();
  static const int kEnvIpv4MulticastGroupAddrFieldNumber = 7;
  const ::std::string& env_ipv4_multicast_group_addr() const;
  void set_env_ipv4_multicast_group_addr(const ::std::string& value);
  #if LANG_CXX11
  void set_env_ipv4_multicast_group_addr(::std::string&& value);
  #endif
  void set_env_ipv4_multicast_group_addr(const char* value);
  void set_env_ipv4_multicast_group_addr(const void* value, size_t size);
  ::std::string* mutable_env_ipv4_multicast_group_addr();
  ::std::string* release_env_ipv4_multicast_group_addr();
  void set_allocated_env_ipv4_multicast_group_addr(::std::string* env_ipv4_multicast_group_addr);

  // required bytes env_ipv6_multicast_group_addr = 11 [default = ""];
  bool has_env_ipv6_multicast_group_addr() const;
  void clear_env_ipv6_multicast_group_addr();
  static const int kEnvIpv6MulticastGroupAddrFieldNumber = 11;
  const ::std::string& env_ipv6_multicast_group_addr() const;
  void set_env_ipv6_multicast_group_addr(const ::std::string& value);
  #if LANG_CXX11
  void set_env_ipv6_multicast_group_addr(::std::string&& value);
  #endif
  void set_env_ipv6_multicast_group_addr(const char* value);
  void set_env_ipv6_multicast_group_addr(const void* value, size_t size);
  ::std::string* mutable_env_ipv6_multicast_group_addr();
  ::std::string* release_env_ipv6_multicast_group_addr();
  void set_allocated_env_ipv6_multicast_group_addr(::std::string* env_ipv6_multicast_group_addr);

  // required bytes env_host_name = 19 [default = ""];
  bool has_env_host_name() const;
  void clear_env_host_name();
  static const int kEnvHostNameFieldNumber = 19;
  const ::std::string& env_host_name() const;
  void set_env_host_name(const ::std::string& value);
  #if LANG_CXX11
  void set_env_host_name(::std::string&& value);
  #endif
  void set_env_host_name(const char* value);
  void set_env_host_name(const void* value, size_t size);
  ::std::string* mutable_env_host_name();
  ::std::string* release_env_host_name();
  void set_allocated_env_host_name(::std::string* env_host_name);

  // required bytes env_ca_cert_file = 20 [default = ""];
  bool has_env_ca_cert_file() const;
  void clear_env_ca_cert_file();
  static const int kEnvCaCertFileFieldNumber = 20;
  const ::std::string& env_ca_cert_file() const;
  void set_env_ca_cert_file(const ::std::string& value);
  #if LANG_CXX11
  void set_env_ca_cert_file(::std::string&& value);
  #endif
  void set_env_ca_cert_file(const char* value);
  void set_env_ca_cert_file(const void* value, size_t size);
  ::std::string* mutable_env_ca_cert_file();
  ::std::string* release_env_ca_cert_file();
  void set_allocated_env_ca_cert_file(::std::string* env_ca_cert_file);

  // required bytes env_ca_priv_key_file = 21 [default = ""];
  bool has_env_ca_priv_key_file() const;
  void clear_env_ca_priv_key_file();
  static const int kEnvCaPrivKeyFileFieldNumber = 21;
  const ::std::string& env_ca_priv_key_file() const;
  void set_env_ca_priv_key_file(const ::std::string& value);
  #if LANG_CXX11
  void set_env_ca_priv_key_file(::std::string&& value);
  #endif
  void set_env_ca_priv_key_file(const char* value);
  void set_env_ca_priv_key_file(const void* value, size_t size);
  ::std::string* mutable_env_ca_priv_key_file();
  ::std::string* release_env_ca_priv_key_file();
  void set_allocated_env_ca_priv_key_file(::std::string* env_ca_priv_key_file);

  // required bytes env_cert_info = 22 [default = ""];
  bool has_env_cert_info() const;
  void clear_env_cert_info();
  static const int kEnvCertInfoFieldNumber = 22;
  const ::std::string& env_cert_info() const;
  void set_env_cert_info(const ::std::string& value);
  #if LANG_CXX11
  void set_env_cert_info(::std::string&& value);
  #endif
  void set_env_cert_info(const char* value);
  void set_env_cert_info(const void* value, size_t size);
  ::std::string* mutable_env_cert_info();
  ::std::string* release_env_cert_info();
  void set_allocated_env_cert_info(::std::string* env_cert_info);

  // required int32 env_ipv4_broadcast_port = 8 [default = 0];
  bool has_env_ipv4_broadcast_port() const;
  void clear_env_ipv4_broadcast_port();
  static const int kEnvIpv4BroadcastPortFieldNumber = 8;
  ::google::protobuf::int32 env_ipv4_broadcast_port() const;
  void set_env_ipv4_broadcast_port(::google::protobuf::int32 value);

  // required int32 env_ipv4_multicast_port = 9 [default = 0];
  bool has_env_ipv4_multicast_port() const;
  void clear_env_ipv4_multicast_port();
  static const int kEnvIpv4MulticastPortFieldNumber = 9;
  ::google::protobuf::int32 env_ipv4_multicast_port() const;
  void set_env_ipv4_multicast_port(::google::protobuf::int32 value);

  // required int32 env_ipv4_stream_port = 10 [default = 0];
  bool has_env_ipv4_stream_port() const;
  void clear_env_ipv4_stream_port();
  static const int kEnvIpv4StreamPortFieldNumber = 10;
  ::google::protobuf::int32 env_ipv4_stream_port() const;
  void set_env_ipv4_stream_port(::google::protobuf::int32 value);

  // required int32 env_ipv6_multicast_port = 12 [default = 0];
  bool has_env_ipv6_multicast_port() const;
  void clear_env_ipv6_multicast_port();
  static const int kEnvIpv6MulticastPortFieldNumber = 12;
  ::google::protobuf::int32 env_ipv6_multicast_port() const;
  void set_env_ipv6_multicast_port(::google::protobuf::int32 value);

  // required int32 env_ipv6_stream_port = 13 [default = 0];
  bool has_env_ipv6_stream_port() const;
  void clear_env_ipv6_stream_port();
  static const int kEnvIpv6StreamPortFieldNumber = 13;
  ::google::protobuf::int32 env_ipv6_stream_port() const;
  void set_env_ipv6_stream_port(::google::protobuf::int32 value);

  // required bool env_ipv6_enabled = 15 [default = false];
  bool has_env_ipv6_enabled() const;
  void clear_env_ipv6_enabled();
  static const int kEnvIpv6EnabledFieldNumber = 15;
  bool env_ipv6_enabled() const;
  void set_env_ipv6_enabled(bool value);

  // required uint64 env_cert_exp_time = 23 [default = 0];
  bool has_env_cert_exp_time() const;
  void clear_env_cert_exp_time();
  static const int kEnvCertExpTimeFieldNumber = 23;
  ::google::protobuf::uint64 env_cert_exp_time() const;
  void set_env_cert_exp_time(::google::protobuf::uint64 value);

  // required int32 env_max_buffsize = 16 [default = 0];
  bool has_env_max_buffsize() const;
  void clear_env_max_buffsize();
  static const int kEnvMaxBuffsizeFieldNumber = 16;
  ::google::protobuf::int32 env_max_buffsize() const;
  void set_env_max_buffsize(::google::protobuf::int32 value);

  // required int32 env_pid = 18 [default = -1];
  bool has_env_pid() const;
  void clear_env_pid();
  static const int kEnvPidFieldNumber = 18;
  ::google::protobuf::int32 env_pid() const;
  void set_env_pid(::google::protobuf::int32 value);

  // required bool env_ipv4_enabled = 14 [default = true];
  bool has_env_ipv4_enabled() const;
  void clear_env_ipv4_enabled();
  static const int kEnvIpv4EnabledFieldNumber = 14;
  bool env_ipv4_enabled() const;
  void set_env_ipv4_enabled(bool value);

  // required uint32 env_broadcast_interval_ms = 17 [default = 1000];
  bool has_env_broadcast_interval_ms() const;
  void clear_env_broadcast_interval_ms();
  static const int kEnvBroadcastIntervalMsFieldNumber = 17;
  ::google::protobuf::uint32 env_broadcast_interval_ms() const;
  void set_env_broadcast_interval_ms(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:env_config_t)
 private:
  void set_has_env_name();
  void clear_has_env_name();
  void set_has_env_headers_path();
  void clear_has_env_headers_path();
  void set_has_env_mountpoint();
  void clear_has_env_mountpoint();
  void set_has_env_components_path();
  void clear_has_env_components_path();
  void set_has_env_x509_certificate_path();
  void clear_has_env_x509_certificate_path();
  void set_has_env_network_ifname();
  void clear_has_env_network_ifname();
  void set_has_env_ipv4_multicast_group_addr();
  void clear_has_env_ipv4_multicast_group_addr();
  void set_has_env_ipv4_broadcast_port();
  void clear_has_env_ipv4_broadcast_port();
  void set_has_env_ipv4_multicast_port();
  void clear_has_env_ipv4_multicast_port();
  void set_has_env_ipv4_stream_port();
  void clear_has_env_ipv4_stream_port();
  void set_has_env_ipv6_multicast_group_addr();
  void clear_has_env_ipv6_multicast_group_addr();
  void set_has_env_ipv6_multicast_port();
  void clear_has_env_ipv6_multicast_port();
  void set_has_env_ipv6_stream_port();
  void clear_has_env_ipv6_stream_port();
  void set_has_env_ipv4_enabled();
  void clear_has_env_ipv4_enabled();
  void set_has_env_ipv6_enabled();
  void clear_has_env_ipv6_enabled();
  void set_has_env_max_buffsize();
  void clear_has_env_max_buffsize();
  void set_has_env_broadcast_interval_ms();
  void clear_has_env_broadcast_interval_ms();
  void set_has_env_pid();
  void clear_has_env_pid();
  void set_has_env_host_name();
  void clear_has_env_host_name();
  void set_has_env_ca_cert_file();
  void clear_has_env_ca_cert_file();
  void set_has_env_ca_priv_key_file();
  void clear_has_env_ca_priv_key_file();
  void set_has_env_cert_info();
  void clear_has_env_cert_info();
  void set_has_env_cert_exp_time();
  void clear_has_env_cert_exp_time();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr env_name_;
  ::google::protobuf::internal::ArenaStringPtr env_headers_path_;
  ::google::protobuf::internal::ArenaStringPtr env_mountpoint_;
  ::google::protobuf::internal::ArenaStringPtr env_components_path_;
  ::google::protobuf::internal::ArenaStringPtr env_x509_certificate_path_;
  ::google::protobuf::internal::ArenaStringPtr env_network_ifname_;
  ::google::protobuf::internal::ArenaStringPtr env_ipv4_multicast_group_addr_;
  ::google::protobuf::internal::ArenaStringPtr env_ipv6_multicast_group_addr_;
  ::google::protobuf::internal::ArenaStringPtr env_host_name_;
  ::google::protobuf::internal::ArenaStringPtr env_ca_cert_file_;
  ::google::protobuf::internal::ArenaStringPtr env_ca_priv_key_file_;
  ::google::protobuf::internal::ArenaStringPtr env_cert_info_;
  ::google::protobuf::int32 env_ipv4_broadcast_port_;
  ::google::protobuf::int32 env_ipv4_multicast_port_;
  ::google::protobuf::int32 env_ipv4_stream_port_;
  ::google::protobuf::int32 env_ipv6_multicast_port_;
  ::google::protobuf::int32 env_ipv6_stream_port_;
  bool env_ipv6_enabled_;
  ::google::protobuf::uint64 env_cert_exp_time_;
  ::google::protobuf::int32 env_max_buffsize_;
  ::google::protobuf::int32 env_pid_;
  bool env_ipv4_enabled_;
  ::google::protobuf::uint32 env_broadcast_interval_ms_;
  friend struct ::protobuf_env_5finfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// env_config_header_t

// required bytes env_name = 1 [default = ""];
inline bool env_config_header_t::has_env_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void env_config_header_t::set_has_env_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void env_config_header_t::clear_has_env_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void env_config_header_t::clear_env_name() {
  env_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_name();
}
inline const ::std::string& env_config_header_t::env_name() const {
  // @@protoc_insertion_point(field_get:env_config_header_t.env_name)
  return env_name_.GetNoArena();
}
inline void env_config_header_t::set_env_name(const ::std::string& value) {
  set_has_env_name();
  env_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_header_t.env_name)
}
#if LANG_CXX11
inline void env_config_header_t::set_env_name(::std::string&& value) {
  set_has_env_name();
  env_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_header_t.env_name)
}
#endif
inline void env_config_header_t::set_env_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_name();
  env_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_header_t.env_name)
}
inline void env_config_header_t::set_env_name(const void* value, size_t size) {
  set_has_env_name();
  env_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_header_t.env_name)
}
inline ::std::string* env_config_header_t::mutable_env_name() {
  set_has_env_name();
  // @@protoc_insertion_point(field_mutable:env_config_header_t.env_name)
  return env_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_header_t::release_env_name() {
  // @@protoc_insertion_point(field_release:env_config_header_t.env_name)
  if (!has_env_name()) {
    return NULL;
  }
  clear_has_env_name();
  return env_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_header_t::set_allocated_env_name(::std::string* env_name) {
  if (env_name != NULL) {
    set_has_env_name();
  } else {
    clear_has_env_name();
  }
  env_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_name);
  // @@protoc_insertion_point(field_set_allocated:env_config_header_t.env_name)
}

// required int32 env_ipv4_stream_port = 2 [default = 0];
inline bool env_config_header_t::has_env_ipv4_stream_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void env_config_header_t::set_has_env_ipv4_stream_port() {
  _has_bits_[0] |= 0x00000008u;
}
inline void env_config_header_t::clear_has_env_ipv4_stream_port() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void env_config_header_t::clear_env_ipv4_stream_port() {
  env_ipv4_stream_port_ = 0;
  clear_has_env_ipv4_stream_port();
}
inline ::google::protobuf::int32 env_config_header_t::env_ipv4_stream_port() const {
  // @@protoc_insertion_point(field_get:env_config_header_t.env_ipv4_stream_port)
  return env_ipv4_stream_port_;
}
inline void env_config_header_t::set_env_ipv4_stream_port(::google::protobuf::int32 value) {
  set_has_env_ipv4_stream_port();
  env_ipv4_stream_port_ = value;
  // @@protoc_insertion_point(field_set:env_config_header_t.env_ipv4_stream_port)
}

// required int32 env_ipv6_stream_port = 3 [default = 0];
inline bool env_config_header_t::has_env_ipv6_stream_port() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void env_config_header_t::set_has_env_ipv6_stream_port() {
  _has_bits_[0] |= 0x00000010u;
}
inline void env_config_header_t::clear_has_env_ipv6_stream_port() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void env_config_header_t::clear_env_ipv6_stream_port() {
  env_ipv6_stream_port_ = 0;
  clear_has_env_ipv6_stream_port();
}
inline ::google::protobuf::int32 env_config_header_t::env_ipv6_stream_port() const {
  // @@protoc_insertion_point(field_get:env_config_header_t.env_ipv6_stream_port)
  return env_ipv6_stream_port_;
}
inline void env_config_header_t::set_env_ipv6_stream_port(::google::protobuf::int32 value) {
  set_has_env_ipv6_stream_port();
  env_ipv6_stream_port_ = value;
  // @@protoc_insertion_point(field_set:env_config_header_t.env_ipv6_stream_port)
}

// required int32 env_pid = 4 [default = 0];
inline bool env_config_header_t::has_env_pid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void env_config_header_t::set_has_env_pid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void env_config_header_t::clear_has_env_pid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void env_config_header_t::clear_env_pid() {
  env_pid_ = 0;
  clear_has_env_pid();
}
inline ::google::protobuf::int32 env_config_header_t::env_pid() const {
  // @@protoc_insertion_point(field_get:env_config_header_t.env_pid)
  return env_pid_;
}
inline void env_config_header_t::set_env_pid(::google::protobuf::int32 value) {
  set_has_env_pid();
  env_pid_ = value;
  // @@protoc_insertion_point(field_set:env_config_header_t.env_pid)
}

// required bytes env_host_name = 5 [default = ""];
inline bool env_config_header_t::has_env_host_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void env_config_header_t::set_has_env_host_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void env_config_header_t::clear_has_env_host_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void env_config_header_t::clear_env_host_name() {
  env_host_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_host_name();
}
inline const ::std::string& env_config_header_t::env_host_name() const {
  // @@protoc_insertion_point(field_get:env_config_header_t.env_host_name)
  return env_host_name_.GetNoArena();
}
inline void env_config_header_t::set_env_host_name(const ::std::string& value) {
  set_has_env_host_name();
  env_host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_header_t.env_host_name)
}
#if LANG_CXX11
inline void env_config_header_t::set_env_host_name(::std::string&& value) {
  set_has_env_host_name();
  env_host_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_header_t.env_host_name)
}
#endif
inline void env_config_header_t::set_env_host_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_host_name();
  env_host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_header_t.env_host_name)
}
inline void env_config_header_t::set_env_host_name(const void* value, size_t size) {
  set_has_env_host_name();
  env_host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_header_t.env_host_name)
}
inline ::std::string* env_config_header_t::mutable_env_host_name() {
  set_has_env_host_name();
  // @@protoc_insertion_point(field_mutable:env_config_header_t.env_host_name)
  return env_host_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_header_t::release_env_host_name() {
  // @@protoc_insertion_point(field_release:env_config_header_t.env_host_name)
  if (!has_env_host_name()) {
    return NULL;
  }
  clear_has_env_host_name();
  return env_host_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_header_t::set_allocated_env_host_name(::std::string* env_host_name) {
  if (env_host_name != NULL) {
    set_has_env_host_name();
  } else {
    clear_has_env_host_name();
  }
  env_host_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_host_name);
  // @@protoc_insertion_point(field_set_allocated:env_config_header_t.env_host_name)
}

// required bytes env_invite = 6 [default = ""];
inline bool env_config_header_t::has_env_invite() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void env_config_header_t::set_has_env_invite() {
  _has_bits_[0] |= 0x00000004u;
}
inline void env_config_header_t::clear_has_env_invite() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void env_config_header_t::clear_env_invite() {
  env_invite_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_invite();
}
inline const ::std::string& env_config_header_t::env_invite() const {
  // @@protoc_insertion_point(field_get:env_config_header_t.env_invite)
  return env_invite_.GetNoArena();
}
inline void env_config_header_t::set_env_invite(const ::std::string& value) {
  set_has_env_invite();
  env_invite_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_header_t.env_invite)
}
#if LANG_CXX11
inline void env_config_header_t::set_env_invite(::std::string&& value) {
  set_has_env_invite();
  env_invite_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_header_t.env_invite)
}
#endif
inline void env_config_header_t::set_env_invite(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_invite();
  env_invite_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_header_t.env_invite)
}
inline void env_config_header_t::set_env_invite(const void* value, size_t size) {
  set_has_env_invite();
  env_invite_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_header_t.env_invite)
}
inline ::std::string* env_config_header_t::mutable_env_invite() {
  set_has_env_invite();
  // @@protoc_insertion_point(field_mutable:env_config_header_t.env_invite)
  return env_invite_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_header_t::release_env_invite() {
  // @@protoc_insertion_point(field_release:env_config_header_t.env_invite)
  if (!has_env_invite()) {
    return NULL;
  }
  clear_has_env_invite();
  return env_invite_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_header_t::set_allocated_env_invite(::std::string* env_invite) {
  if (env_invite != NULL) {
    set_has_env_invite();
  } else {
    clear_has_env_invite();
  }
  env_invite_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_invite);
  // @@protoc_insertion_point(field_set_allocated:env_config_header_t.env_invite)
}

// -------------------------------------------------------------------

// env_config_t

// required bytes env_name = 1 [default = ""];
inline bool env_config_t::has_env_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void env_config_t::set_has_env_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void env_config_t::clear_has_env_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void env_config_t::clear_env_name() {
  env_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_name();
}
inline const ::std::string& env_config_t::env_name() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_name)
  return env_name_.GetNoArena();
}
inline void env_config_t::set_env_name(const ::std::string& value) {
  set_has_env_name();
  env_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_name)
}
#if LANG_CXX11
inline void env_config_t::set_env_name(::std::string&& value) {
  set_has_env_name();
  env_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_name)
}
#endif
inline void env_config_t::set_env_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_name();
  env_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_name)
}
inline void env_config_t::set_env_name(const void* value, size_t size) {
  set_has_env_name();
  env_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_name)
}
inline ::std::string* env_config_t::mutable_env_name() {
  set_has_env_name();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_name)
  return env_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_name() {
  // @@protoc_insertion_point(field_release:env_config_t.env_name)
  if (!has_env_name()) {
    return NULL;
  }
  clear_has_env_name();
  return env_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_name(::std::string* env_name) {
  if (env_name != NULL) {
    set_has_env_name();
  } else {
    clear_has_env_name();
  }
  env_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_name);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_name)
}

// required bytes env_headers_path = 2 [default = ""];
inline bool env_config_t::has_env_headers_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void env_config_t::set_has_env_headers_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void env_config_t::clear_has_env_headers_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void env_config_t::clear_env_headers_path() {
  env_headers_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_headers_path();
}
inline const ::std::string& env_config_t::env_headers_path() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_headers_path)
  return env_headers_path_.GetNoArena();
}
inline void env_config_t::set_env_headers_path(const ::std::string& value) {
  set_has_env_headers_path();
  env_headers_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_headers_path)
}
#if LANG_CXX11
inline void env_config_t::set_env_headers_path(::std::string&& value) {
  set_has_env_headers_path();
  env_headers_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_headers_path)
}
#endif
inline void env_config_t::set_env_headers_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_headers_path();
  env_headers_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_headers_path)
}
inline void env_config_t::set_env_headers_path(const void* value, size_t size) {
  set_has_env_headers_path();
  env_headers_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_headers_path)
}
inline ::std::string* env_config_t::mutable_env_headers_path() {
  set_has_env_headers_path();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_headers_path)
  return env_headers_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_headers_path() {
  // @@protoc_insertion_point(field_release:env_config_t.env_headers_path)
  if (!has_env_headers_path()) {
    return NULL;
  }
  clear_has_env_headers_path();
  return env_headers_path_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_headers_path(::std::string* env_headers_path) {
  if (env_headers_path != NULL) {
    set_has_env_headers_path();
  } else {
    clear_has_env_headers_path();
  }
  env_headers_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_headers_path);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_headers_path)
}

// required bytes env_mountpoint = 3 [default = ""];
inline bool env_config_t::has_env_mountpoint() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void env_config_t::set_has_env_mountpoint() {
  _has_bits_[0] |= 0x00000004u;
}
inline void env_config_t::clear_has_env_mountpoint() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void env_config_t::clear_env_mountpoint() {
  env_mountpoint_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_mountpoint();
}
inline const ::std::string& env_config_t::env_mountpoint() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_mountpoint)
  return env_mountpoint_.GetNoArena();
}
inline void env_config_t::set_env_mountpoint(const ::std::string& value) {
  set_has_env_mountpoint();
  env_mountpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_mountpoint)
}
#if LANG_CXX11
inline void env_config_t::set_env_mountpoint(::std::string&& value) {
  set_has_env_mountpoint();
  env_mountpoint_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_mountpoint)
}
#endif
inline void env_config_t::set_env_mountpoint(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_mountpoint();
  env_mountpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_mountpoint)
}
inline void env_config_t::set_env_mountpoint(const void* value, size_t size) {
  set_has_env_mountpoint();
  env_mountpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_mountpoint)
}
inline ::std::string* env_config_t::mutable_env_mountpoint() {
  set_has_env_mountpoint();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_mountpoint)
  return env_mountpoint_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_mountpoint() {
  // @@protoc_insertion_point(field_release:env_config_t.env_mountpoint)
  if (!has_env_mountpoint()) {
    return NULL;
  }
  clear_has_env_mountpoint();
  return env_mountpoint_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_mountpoint(::std::string* env_mountpoint) {
  if (env_mountpoint != NULL) {
    set_has_env_mountpoint();
  } else {
    clear_has_env_mountpoint();
  }
  env_mountpoint_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_mountpoint);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_mountpoint)
}

// required bytes env_components_path = 4 [default = ""];
inline bool env_config_t::has_env_components_path() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void env_config_t::set_has_env_components_path() {
  _has_bits_[0] |= 0x00000008u;
}
inline void env_config_t::clear_has_env_components_path() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void env_config_t::clear_env_components_path() {
  env_components_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_components_path();
}
inline const ::std::string& env_config_t::env_components_path() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_components_path)
  return env_components_path_.GetNoArena();
}
inline void env_config_t::set_env_components_path(const ::std::string& value) {
  set_has_env_components_path();
  env_components_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_components_path)
}
#if LANG_CXX11
inline void env_config_t::set_env_components_path(::std::string&& value) {
  set_has_env_components_path();
  env_components_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_components_path)
}
#endif
inline void env_config_t::set_env_components_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_components_path();
  env_components_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_components_path)
}
inline void env_config_t::set_env_components_path(const void* value, size_t size) {
  set_has_env_components_path();
  env_components_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_components_path)
}
inline ::std::string* env_config_t::mutable_env_components_path() {
  set_has_env_components_path();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_components_path)
  return env_components_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_components_path() {
  // @@protoc_insertion_point(field_release:env_config_t.env_components_path)
  if (!has_env_components_path()) {
    return NULL;
  }
  clear_has_env_components_path();
  return env_components_path_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_components_path(::std::string* env_components_path) {
  if (env_components_path != NULL) {
    set_has_env_components_path();
  } else {
    clear_has_env_components_path();
  }
  env_components_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_components_path);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_components_path)
}

// required bytes env_x509_certificate_path = 5 [default = ""];
inline bool env_config_t::has_env_x509_certificate_path() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void env_config_t::set_has_env_x509_certificate_path() {
  _has_bits_[0] |= 0x00000010u;
}
inline void env_config_t::clear_has_env_x509_certificate_path() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void env_config_t::clear_env_x509_certificate_path() {
  env_x509_certificate_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_x509_certificate_path();
}
inline const ::std::string& env_config_t::env_x509_certificate_path() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_x509_certificate_path)
  return env_x509_certificate_path_.GetNoArena();
}
inline void env_config_t::set_env_x509_certificate_path(const ::std::string& value) {
  set_has_env_x509_certificate_path();
  env_x509_certificate_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_x509_certificate_path)
}
#if LANG_CXX11
inline void env_config_t::set_env_x509_certificate_path(::std::string&& value) {
  set_has_env_x509_certificate_path();
  env_x509_certificate_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_x509_certificate_path)
}
#endif
inline void env_config_t::set_env_x509_certificate_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_x509_certificate_path();
  env_x509_certificate_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_x509_certificate_path)
}
inline void env_config_t::set_env_x509_certificate_path(const void* value, size_t size) {
  set_has_env_x509_certificate_path();
  env_x509_certificate_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_x509_certificate_path)
}
inline ::std::string* env_config_t::mutable_env_x509_certificate_path() {
  set_has_env_x509_certificate_path();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_x509_certificate_path)
  return env_x509_certificate_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_x509_certificate_path() {
  // @@protoc_insertion_point(field_release:env_config_t.env_x509_certificate_path)
  if (!has_env_x509_certificate_path()) {
    return NULL;
  }
  clear_has_env_x509_certificate_path();
  return env_x509_certificate_path_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_x509_certificate_path(::std::string* env_x509_certificate_path) {
  if (env_x509_certificate_path != NULL) {
    set_has_env_x509_certificate_path();
  } else {
    clear_has_env_x509_certificate_path();
  }
  env_x509_certificate_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_x509_certificate_path);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_x509_certificate_path)
}

// required bytes env_network_ifname = 6 [default = ""];
inline bool env_config_t::has_env_network_ifname() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void env_config_t::set_has_env_network_ifname() {
  _has_bits_[0] |= 0x00000020u;
}
inline void env_config_t::clear_has_env_network_ifname() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void env_config_t::clear_env_network_ifname() {
  env_network_ifname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_network_ifname();
}
inline const ::std::string& env_config_t::env_network_ifname() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_network_ifname)
  return env_network_ifname_.GetNoArena();
}
inline void env_config_t::set_env_network_ifname(const ::std::string& value) {
  set_has_env_network_ifname();
  env_network_ifname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_network_ifname)
}
#if LANG_CXX11
inline void env_config_t::set_env_network_ifname(::std::string&& value) {
  set_has_env_network_ifname();
  env_network_ifname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_network_ifname)
}
#endif
inline void env_config_t::set_env_network_ifname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_network_ifname();
  env_network_ifname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_network_ifname)
}
inline void env_config_t::set_env_network_ifname(const void* value, size_t size) {
  set_has_env_network_ifname();
  env_network_ifname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_network_ifname)
}
inline ::std::string* env_config_t::mutable_env_network_ifname() {
  set_has_env_network_ifname();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_network_ifname)
  return env_network_ifname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_network_ifname() {
  // @@protoc_insertion_point(field_release:env_config_t.env_network_ifname)
  if (!has_env_network_ifname()) {
    return NULL;
  }
  clear_has_env_network_ifname();
  return env_network_ifname_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_network_ifname(::std::string* env_network_ifname) {
  if (env_network_ifname != NULL) {
    set_has_env_network_ifname();
  } else {
    clear_has_env_network_ifname();
  }
  env_network_ifname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_network_ifname);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_network_ifname)
}

// required bytes env_ipv4_multicast_group_addr = 7 [default = ""];
inline bool env_config_t::has_env_ipv4_multicast_group_addr() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void env_config_t::set_has_env_ipv4_multicast_group_addr() {
  _has_bits_[0] |= 0x00000040u;
}
inline void env_config_t::clear_has_env_ipv4_multicast_group_addr() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void env_config_t::clear_env_ipv4_multicast_group_addr() {
  env_ipv4_multicast_group_addr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_ipv4_multicast_group_addr();
}
inline const ::std::string& env_config_t::env_ipv4_multicast_group_addr() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv4_multicast_group_addr)
  return env_ipv4_multicast_group_addr_.GetNoArena();
}
inline void env_config_t::set_env_ipv4_multicast_group_addr(const ::std::string& value) {
  set_has_env_ipv4_multicast_group_addr();
  env_ipv4_multicast_group_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv4_multicast_group_addr)
}
#if LANG_CXX11
inline void env_config_t::set_env_ipv4_multicast_group_addr(::std::string&& value) {
  set_has_env_ipv4_multicast_group_addr();
  env_ipv4_multicast_group_addr_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_ipv4_multicast_group_addr)
}
#endif
inline void env_config_t::set_env_ipv4_multicast_group_addr(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_ipv4_multicast_group_addr();
  env_ipv4_multicast_group_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_ipv4_multicast_group_addr)
}
inline void env_config_t::set_env_ipv4_multicast_group_addr(const void* value, size_t size) {
  set_has_env_ipv4_multicast_group_addr();
  env_ipv4_multicast_group_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_ipv4_multicast_group_addr)
}
inline ::std::string* env_config_t::mutable_env_ipv4_multicast_group_addr() {
  set_has_env_ipv4_multicast_group_addr();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_ipv4_multicast_group_addr)
  return env_ipv4_multicast_group_addr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_ipv4_multicast_group_addr() {
  // @@protoc_insertion_point(field_release:env_config_t.env_ipv4_multicast_group_addr)
  if (!has_env_ipv4_multicast_group_addr()) {
    return NULL;
  }
  clear_has_env_ipv4_multicast_group_addr();
  return env_ipv4_multicast_group_addr_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_ipv4_multicast_group_addr(::std::string* env_ipv4_multicast_group_addr) {
  if (env_ipv4_multicast_group_addr != NULL) {
    set_has_env_ipv4_multicast_group_addr();
  } else {
    clear_has_env_ipv4_multicast_group_addr();
  }
  env_ipv4_multicast_group_addr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_ipv4_multicast_group_addr);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_ipv4_multicast_group_addr)
}

// required int32 env_ipv4_broadcast_port = 8 [default = 0];
inline bool env_config_t::has_env_ipv4_broadcast_port() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void env_config_t::set_has_env_ipv4_broadcast_port() {
  _has_bits_[0] |= 0x00001000u;
}
inline void env_config_t::clear_has_env_ipv4_broadcast_port() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void env_config_t::clear_env_ipv4_broadcast_port() {
  env_ipv4_broadcast_port_ = 0;
  clear_has_env_ipv4_broadcast_port();
}
inline ::google::protobuf::int32 env_config_t::env_ipv4_broadcast_port() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv4_broadcast_port)
  return env_ipv4_broadcast_port_;
}
inline void env_config_t::set_env_ipv4_broadcast_port(::google::protobuf::int32 value) {
  set_has_env_ipv4_broadcast_port();
  env_ipv4_broadcast_port_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv4_broadcast_port)
}

// required int32 env_ipv4_multicast_port = 9 [default = 0];
inline bool env_config_t::has_env_ipv4_multicast_port() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void env_config_t::set_has_env_ipv4_multicast_port() {
  _has_bits_[0] |= 0x00002000u;
}
inline void env_config_t::clear_has_env_ipv4_multicast_port() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void env_config_t::clear_env_ipv4_multicast_port() {
  env_ipv4_multicast_port_ = 0;
  clear_has_env_ipv4_multicast_port();
}
inline ::google::protobuf::int32 env_config_t::env_ipv4_multicast_port() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv4_multicast_port)
  return env_ipv4_multicast_port_;
}
inline void env_config_t::set_env_ipv4_multicast_port(::google::protobuf::int32 value) {
  set_has_env_ipv4_multicast_port();
  env_ipv4_multicast_port_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv4_multicast_port)
}

// required int32 env_ipv4_stream_port = 10 [default = 0];
inline bool env_config_t::has_env_ipv4_stream_port() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void env_config_t::set_has_env_ipv4_stream_port() {
  _has_bits_[0] |= 0x00004000u;
}
inline void env_config_t::clear_has_env_ipv4_stream_port() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void env_config_t::clear_env_ipv4_stream_port() {
  env_ipv4_stream_port_ = 0;
  clear_has_env_ipv4_stream_port();
}
inline ::google::protobuf::int32 env_config_t::env_ipv4_stream_port() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv4_stream_port)
  return env_ipv4_stream_port_;
}
inline void env_config_t::set_env_ipv4_stream_port(::google::protobuf::int32 value) {
  set_has_env_ipv4_stream_port();
  env_ipv4_stream_port_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv4_stream_port)
}

// required bytes env_ipv6_multicast_group_addr = 11 [default = ""];
inline bool env_config_t::has_env_ipv6_multicast_group_addr() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void env_config_t::set_has_env_ipv6_multicast_group_addr() {
  _has_bits_[0] |= 0x00000080u;
}
inline void env_config_t::clear_has_env_ipv6_multicast_group_addr() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void env_config_t::clear_env_ipv6_multicast_group_addr() {
  env_ipv6_multicast_group_addr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_ipv6_multicast_group_addr();
}
inline const ::std::string& env_config_t::env_ipv6_multicast_group_addr() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv6_multicast_group_addr)
  return env_ipv6_multicast_group_addr_.GetNoArena();
}
inline void env_config_t::set_env_ipv6_multicast_group_addr(const ::std::string& value) {
  set_has_env_ipv6_multicast_group_addr();
  env_ipv6_multicast_group_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv6_multicast_group_addr)
}
#if LANG_CXX11
inline void env_config_t::set_env_ipv6_multicast_group_addr(::std::string&& value) {
  set_has_env_ipv6_multicast_group_addr();
  env_ipv6_multicast_group_addr_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_ipv6_multicast_group_addr)
}
#endif
inline void env_config_t::set_env_ipv6_multicast_group_addr(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_ipv6_multicast_group_addr();
  env_ipv6_multicast_group_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_ipv6_multicast_group_addr)
}
inline void env_config_t::set_env_ipv6_multicast_group_addr(const void* value, size_t size) {
  set_has_env_ipv6_multicast_group_addr();
  env_ipv6_multicast_group_addr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_ipv6_multicast_group_addr)
}
inline ::std::string* env_config_t::mutable_env_ipv6_multicast_group_addr() {
  set_has_env_ipv6_multicast_group_addr();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_ipv6_multicast_group_addr)
  return env_ipv6_multicast_group_addr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_ipv6_multicast_group_addr() {
  // @@protoc_insertion_point(field_release:env_config_t.env_ipv6_multicast_group_addr)
  if (!has_env_ipv6_multicast_group_addr()) {
    return NULL;
  }
  clear_has_env_ipv6_multicast_group_addr();
  return env_ipv6_multicast_group_addr_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_ipv6_multicast_group_addr(::std::string* env_ipv6_multicast_group_addr) {
  if (env_ipv6_multicast_group_addr != NULL) {
    set_has_env_ipv6_multicast_group_addr();
  } else {
    clear_has_env_ipv6_multicast_group_addr();
  }
  env_ipv6_multicast_group_addr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_ipv6_multicast_group_addr);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_ipv6_multicast_group_addr)
}

// required int32 env_ipv6_multicast_port = 12 [default = 0];
inline bool env_config_t::has_env_ipv6_multicast_port() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void env_config_t::set_has_env_ipv6_multicast_port() {
  _has_bits_[0] |= 0x00008000u;
}
inline void env_config_t::clear_has_env_ipv6_multicast_port() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void env_config_t::clear_env_ipv6_multicast_port() {
  env_ipv6_multicast_port_ = 0;
  clear_has_env_ipv6_multicast_port();
}
inline ::google::protobuf::int32 env_config_t::env_ipv6_multicast_port() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv6_multicast_port)
  return env_ipv6_multicast_port_;
}
inline void env_config_t::set_env_ipv6_multicast_port(::google::protobuf::int32 value) {
  set_has_env_ipv6_multicast_port();
  env_ipv6_multicast_port_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv6_multicast_port)
}

// required int32 env_ipv6_stream_port = 13 [default = 0];
inline bool env_config_t::has_env_ipv6_stream_port() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void env_config_t::set_has_env_ipv6_stream_port() {
  _has_bits_[0] |= 0x00010000u;
}
inline void env_config_t::clear_has_env_ipv6_stream_port() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void env_config_t::clear_env_ipv6_stream_port() {
  env_ipv6_stream_port_ = 0;
  clear_has_env_ipv6_stream_port();
}
inline ::google::protobuf::int32 env_config_t::env_ipv6_stream_port() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv6_stream_port)
  return env_ipv6_stream_port_;
}
inline void env_config_t::set_env_ipv6_stream_port(::google::protobuf::int32 value) {
  set_has_env_ipv6_stream_port();
  env_ipv6_stream_port_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv6_stream_port)
}

// required bool env_ipv4_enabled = 14 [default = true];
inline bool env_config_t::has_env_ipv4_enabled() const {
  return (_has_bits_[0] & 0x00200000u) != 0;
}
inline void env_config_t::set_has_env_ipv4_enabled() {
  _has_bits_[0] |= 0x00200000u;
}
inline void env_config_t::clear_has_env_ipv4_enabled() {
  _has_bits_[0] &= ~0x00200000u;
}
inline void env_config_t::clear_env_ipv4_enabled() {
  env_ipv4_enabled_ = true;
  clear_has_env_ipv4_enabled();
}
inline bool env_config_t::env_ipv4_enabled() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv4_enabled)
  return env_ipv4_enabled_;
}
inline void env_config_t::set_env_ipv4_enabled(bool value) {
  set_has_env_ipv4_enabled();
  env_ipv4_enabled_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv4_enabled)
}

// required bool env_ipv6_enabled = 15 [default = false];
inline bool env_config_t::has_env_ipv6_enabled() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void env_config_t::set_has_env_ipv6_enabled() {
  _has_bits_[0] |= 0x00020000u;
}
inline void env_config_t::clear_has_env_ipv6_enabled() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void env_config_t::clear_env_ipv6_enabled() {
  env_ipv6_enabled_ = false;
  clear_has_env_ipv6_enabled();
}
inline bool env_config_t::env_ipv6_enabled() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ipv6_enabled)
  return env_ipv6_enabled_;
}
inline void env_config_t::set_env_ipv6_enabled(bool value) {
  set_has_env_ipv6_enabled();
  env_ipv6_enabled_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_ipv6_enabled)
}

// required int32 env_max_buffsize = 16 [default = 0];
inline bool env_config_t::has_env_max_buffsize() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void env_config_t::set_has_env_max_buffsize() {
  _has_bits_[0] |= 0x00080000u;
}
inline void env_config_t::clear_has_env_max_buffsize() {
  _has_bits_[0] &= ~0x00080000u;
}
inline void env_config_t::clear_env_max_buffsize() {
  env_max_buffsize_ = 0;
  clear_has_env_max_buffsize();
}
inline ::google::protobuf::int32 env_config_t::env_max_buffsize() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_max_buffsize)
  return env_max_buffsize_;
}
inline void env_config_t::set_env_max_buffsize(::google::protobuf::int32 value) {
  set_has_env_max_buffsize();
  env_max_buffsize_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_max_buffsize)
}

// required uint32 env_broadcast_interval_ms = 17 [default = 1000];
inline bool env_config_t::has_env_broadcast_interval_ms() const {
  return (_has_bits_[0] & 0x00400000u) != 0;
}
inline void env_config_t::set_has_env_broadcast_interval_ms() {
  _has_bits_[0] |= 0x00400000u;
}
inline void env_config_t::clear_has_env_broadcast_interval_ms() {
  _has_bits_[0] &= ~0x00400000u;
}
inline void env_config_t::clear_env_broadcast_interval_ms() {
  env_broadcast_interval_ms_ = 1000u;
  clear_has_env_broadcast_interval_ms();
}
inline ::google::protobuf::uint32 env_config_t::env_broadcast_interval_ms() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_broadcast_interval_ms)
  return env_broadcast_interval_ms_;
}
inline void env_config_t::set_env_broadcast_interval_ms(::google::protobuf::uint32 value) {
  set_has_env_broadcast_interval_ms();
  env_broadcast_interval_ms_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_broadcast_interval_ms)
}

// required int32 env_pid = 18 [default = -1];
inline bool env_config_t::has_env_pid() const {
  return (_has_bits_[0] & 0x00100000u) != 0;
}
inline void env_config_t::set_has_env_pid() {
  _has_bits_[0] |= 0x00100000u;
}
inline void env_config_t::clear_has_env_pid() {
  _has_bits_[0] &= ~0x00100000u;
}
inline void env_config_t::clear_env_pid() {
  env_pid_ = -1;
  clear_has_env_pid();
}
inline ::google::protobuf::int32 env_config_t::env_pid() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_pid)
  return env_pid_;
}
inline void env_config_t::set_env_pid(::google::protobuf::int32 value) {
  set_has_env_pid();
  env_pid_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_pid)
}

// required bytes env_host_name = 19 [default = ""];
inline bool env_config_t::has_env_host_name() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void env_config_t::set_has_env_host_name() {
  _has_bits_[0] |= 0x00000100u;
}
inline void env_config_t::clear_has_env_host_name() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void env_config_t::clear_env_host_name() {
  env_host_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_host_name();
}
inline const ::std::string& env_config_t::env_host_name() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_host_name)
  return env_host_name_.GetNoArena();
}
inline void env_config_t::set_env_host_name(const ::std::string& value) {
  set_has_env_host_name();
  env_host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_host_name)
}
#if LANG_CXX11
inline void env_config_t::set_env_host_name(::std::string&& value) {
  set_has_env_host_name();
  env_host_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_host_name)
}
#endif
inline void env_config_t::set_env_host_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_host_name();
  env_host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_host_name)
}
inline void env_config_t::set_env_host_name(const void* value, size_t size) {
  set_has_env_host_name();
  env_host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_host_name)
}
inline ::std::string* env_config_t::mutable_env_host_name() {
  set_has_env_host_name();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_host_name)
  return env_host_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_host_name() {
  // @@protoc_insertion_point(field_release:env_config_t.env_host_name)
  if (!has_env_host_name()) {
    return NULL;
  }
  clear_has_env_host_name();
  return env_host_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_host_name(::std::string* env_host_name) {
  if (env_host_name != NULL) {
    set_has_env_host_name();
  } else {
    clear_has_env_host_name();
  }
  env_host_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_host_name);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_host_name)
}

// required bytes env_ca_cert_file = 20 [default = ""];
inline bool env_config_t::has_env_ca_cert_file() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void env_config_t::set_has_env_ca_cert_file() {
  _has_bits_[0] |= 0x00000200u;
}
inline void env_config_t::clear_has_env_ca_cert_file() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void env_config_t::clear_env_ca_cert_file() {
  env_ca_cert_file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_ca_cert_file();
}
inline const ::std::string& env_config_t::env_ca_cert_file() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ca_cert_file)
  return env_ca_cert_file_.GetNoArena();
}
inline void env_config_t::set_env_ca_cert_file(const ::std::string& value) {
  set_has_env_ca_cert_file();
  env_ca_cert_file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_ca_cert_file)
}
#if LANG_CXX11
inline void env_config_t::set_env_ca_cert_file(::std::string&& value) {
  set_has_env_ca_cert_file();
  env_ca_cert_file_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_ca_cert_file)
}
#endif
inline void env_config_t::set_env_ca_cert_file(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_ca_cert_file();
  env_ca_cert_file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_ca_cert_file)
}
inline void env_config_t::set_env_ca_cert_file(const void* value, size_t size) {
  set_has_env_ca_cert_file();
  env_ca_cert_file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_ca_cert_file)
}
inline ::std::string* env_config_t::mutable_env_ca_cert_file() {
  set_has_env_ca_cert_file();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_ca_cert_file)
  return env_ca_cert_file_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_ca_cert_file() {
  // @@protoc_insertion_point(field_release:env_config_t.env_ca_cert_file)
  if (!has_env_ca_cert_file()) {
    return NULL;
  }
  clear_has_env_ca_cert_file();
  return env_ca_cert_file_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_ca_cert_file(::std::string* env_ca_cert_file) {
  if (env_ca_cert_file != NULL) {
    set_has_env_ca_cert_file();
  } else {
    clear_has_env_ca_cert_file();
  }
  env_ca_cert_file_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_ca_cert_file);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_ca_cert_file)
}

// required bytes env_ca_priv_key_file = 21 [default = ""];
inline bool env_config_t::has_env_ca_priv_key_file() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void env_config_t::set_has_env_ca_priv_key_file() {
  _has_bits_[0] |= 0x00000400u;
}
inline void env_config_t::clear_has_env_ca_priv_key_file() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void env_config_t::clear_env_ca_priv_key_file() {
  env_ca_priv_key_file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_ca_priv_key_file();
}
inline const ::std::string& env_config_t::env_ca_priv_key_file() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_ca_priv_key_file)
  return env_ca_priv_key_file_.GetNoArena();
}
inline void env_config_t::set_env_ca_priv_key_file(const ::std::string& value) {
  set_has_env_ca_priv_key_file();
  env_ca_priv_key_file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_ca_priv_key_file)
}
#if LANG_CXX11
inline void env_config_t::set_env_ca_priv_key_file(::std::string&& value) {
  set_has_env_ca_priv_key_file();
  env_ca_priv_key_file_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_ca_priv_key_file)
}
#endif
inline void env_config_t::set_env_ca_priv_key_file(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_ca_priv_key_file();
  env_ca_priv_key_file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_ca_priv_key_file)
}
inline void env_config_t::set_env_ca_priv_key_file(const void* value, size_t size) {
  set_has_env_ca_priv_key_file();
  env_ca_priv_key_file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_ca_priv_key_file)
}
inline ::std::string* env_config_t::mutable_env_ca_priv_key_file() {
  set_has_env_ca_priv_key_file();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_ca_priv_key_file)
  return env_ca_priv_key_file_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_ca_priv_key_file() {
  // @@protoc_insertion_point(field_release:env_config_t.env_ca_priv_key_file)
  if (!has_env_ca_priv_key_file()) {
    return NULL;
  }
  clear_has_env_ca_priv_key_file();
  return env_ca_priv_key_file_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_ca_priv_key_file(::std::string* env_ca_priv_key_file) {
  if (env_ca_priv_key_file != NULL) {
    set_has_env_ca_priv_key_file();
  } else {
    clear_has_env_ca_priv_key_file();
  }
  env_ca_priv_key_file_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_ca_priv_key_file);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_ca_priv_key_file)
}

// required bytes env_cert_info = 22 [default = ""];
inline bool env_config_t::has_env_cert_info() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void env_config_t::set_has_env_cert_info() {
  _has_bits_[0] |= 0x00000800u;
}
inline void env_config_t::clear_has_env_cert_info() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void env_config_t::clear_env_cert_info() {
  env_cert_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_env_cert_info();
}
inline const ::std::string& env_config_t::env_cert_info() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_cert_info)
  return env_cert_info_.GetNoArena();
}
inline void env_config_t::set_env_cert_info(const ::std::string& value) {
  set_has_env_cert_info();
  env_cert_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:env_config_t.env_cert_info)
}
#if LANG_CXX11
inline void env_config_t::set_env_cert_info(::std::string&& value) {
  set_has_env_cert_info();
  env_cert_info_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:env_config_t.env_cert_info)
}
#endif
inline void env_config_t::set_env_cert_info(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_env_cert_info();
  env_cert_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:env_config_t.env_cert_info)
}
inline void env_config_t::set_env_cert_info(const void* value, size_t size) {
  set_has_env_cert_info();
  env_cert_info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:env_config_t.env_cert_info)
}
inline ::std::string* env_config_t::mutable_env_cert_info() {
  set_has_env_cert_info();
  // @@protoc_insertion_point(field_mutable:env_config_t.env_cert_info)
  return env_cert_info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* env_config_t::release_env_cert_info() {
  // @@protoc_insertion_point(field_release:env_config_t.env_cert_info)
  if (!has_env_cert_info()) {
    return NULL;
  }
  clear_has_env_cert_info();
  return env_cert_info_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void env_config_t::set_allocated_env_cert_info(::std::string* env_cert_info) {
  if (env_cert_info != NULL) {
    set_has_env_cert_info();
  } else {
    clear_has_env_cert_info();
  }
  env_cert_info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), env_cert_info);
  // @@protoc_insertion_point(field_set_allocated:env_config_t.env_cert_info)
}

// required uint64 env_cert_exp_time = 23 [default = 0];
inline bool env_config_t::has_env_cert_exp_time() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void env_config_t::set_has_env_cert_exp_time() {
  _has_bits_[0] |= 0x00040000u;
}
inline void env_config_t::clear_has_env_cert_exp_time() {
  _has_bits_[0] &= ~0x00040000u;
}
inline void env_config_t::clear_env_cert_exp_time() {
  env_cert_exp_time_ = GOOGLE_ULONGLONG(0);
  clear_has_env_cert_exp_time();
}
inline ::google::protobuf::uint64 env_config_t::env_cert_exp_time() const {
  // @@protoc_insertion_point(field_get:env_config_t.env_cert_exp_time)
  return env_cert_exp_time_;
}
inline void env_config_t::set_env_cert_exp_time(::google::protobuf::uint64 value) {
  set_has_env_cert_exp_time();
  env_cert_exp_time_ = value;
  // @@protoc_insertion_point(field_set:env_config_t.env_cert_exp_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_env_5finfo_2eproto
