// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime_info.proto

#ifndef PROTOBUF_INCLUDED_runtime_5finfo_2eproto
#define PROTOBUF_INCLUDED_runtime_5finfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_runtime_5finfo_2eproto 

namespace protobuf_runtime_5finfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_runtime_5finfo_2eproto
class runtime_list_info_t;
class runtime_list_info_tDefaultTypeInternal;
extern runtime_list_info_tDefaultTypeInternal _runtime_list_info_t_default_instance_;
namespace google {
namespace protobuf {
template<> ::runtime_list_info_t* Arena::CreateMaybeMessage<::runtime_list_info_t>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class runtime_list_info_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:runtime_list_info_t) */ {
 public:
  runtime_list_info_t();
  virtual ~runtime_list_info_t();

  runtime_list_info_t(const runtime_list_info_t& from);

  inline runtime_list_info_t& operator=(const runtime_list_info_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  runtime_list_info_t(runtime_list_info_t&& from) noexcept
    : runtime_list_info_t() {
    *this = ::std::move(from);
  }

  inline runtime_list_info_t& operator=(runtime_list_info_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const runtime_list_info_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const runtime_list_info_t* internal_default_instance() {
    return reinterpret_cast<const runtime_list_info_t*>(
               &_runtime_list_info_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(runtime_list_info_t* other);
  friend void swap(runtime_list_info_t& a, runtime_list_info_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline runtime_list_info_t* New() const final {
    return CreateMaybeMessage<runtime_list_info_t>(NULL);
  }

  runtime_list_info_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<runtime_list_info_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const runtime_list_info_t& from);
  void MergeFrom(const runtime_list_info_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(runtime_list_info_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes id = 1 [default = ""];
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const void* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // required bytes name_hash = 2 [default = ""];
  bool has_name_hash() const;
  void clear_name_hash();
  static const int kNameHashFieldNumber = 2;
  const ::std::string& name_hash() const;
  void set_name_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_name_hash(::std::string&& value);
  #endif
  void set_name_hash(const char* value);
  void set_name_hash(const void* value, size_t size);
  ::std::string* mutable_name_hash();
  ::std::string* release_name_hash();
  void set_allocated_name_hash(::std::string* name_hash);

  // required bytes hostid = 3 [default = ""];
  bool has_hostid() const;
  void clear_hostid();
  static const int kHostidFieldNumber = 3;
  const ::std::string& hostid() const;
  void set_hostid(const ::std::string& value);
  #if LANG_CXX11
  void set_hostid(::std::string&& value);
  #endif
  void set_hostid(const char* value);
  void set_hostid(const void* value, size_t size);
  ::std::string* mutable_hostid();
  ::std::string* release_hostid();
  void set_allocated_hostid(::std::string* hostid);

  // required bytes composition_id = 4 [default = ""];
  bool has_composition_id() const;
  void clear_composition_id();
  static const int kCompositionIdFieldNumber = 4;
  const ::std::string& composition_id() const;
  void set_composition_id(const ::std::string& value);
  #if LANG_CXX11
  void set_composition_id(::std::string&& value);
  #endif
  void set_composition_id(const char* value);
  void set_composition_id(const void* value, size_t size);
  ::std::string* mutable_composition_id();
  ::std::string* release_composition_id();
  void set_allocated_composition_id(::std::string* composition_id);

  // required bytes component_id = 5 [default = ""];
  bool has_component_id() const;
  void clear_component_id();
  static const int kComponentIdFieldNumber = 5;
  const ::std::string& component_id() const;
  void set_component_id(const ::std::string& value);
  #if LANG_CXX11
  void set_component_id(::std::string&& value);
  #endif
  void set_component_id(const char* value);
  void set_component_id(const void* value, size_t size);
  ::std::string* mutable_component_id();
  ::std::string* release_component_id();
  void set_allocated_component_id(::std::string* component_id);

  // required bytes thread_id = 7 [default = ""];
  bool has_thread_id() const;
  void clear_thread_id();
  static const int kThreadIdFieldNumber = 7;
  const ::std::string& thread_id() const;
  void set_thread_id(const ::std::string& value);
  #if LANG_CXX11
  void set_thread_id(::std::string&& value);
  #endif
  void set_thread_id(const char* value);
  void set_thread_id(const void* value, size_t size);
  ::std::string* mutable_thread_id();
  ::std::string* release_thread_id();
  void set_allocated_thread_id(::std::string* thread_id);

  // required int32 pid = 6 [default = 0];
  bool has_pid() const;
  void clear_pid();
  static const int kPidFieldNumber = 6;
  ::google::protobuf::int32 pid() const;
  void set_pid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:runtime_list_info_t)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name_hash();
  void clear_has_name_hash();
  void set_has_hostid();
  void clear_has_hostid();
  void set_has_composition_id();
  void clear_has_composition_id();
  void set_has_component_id();
  void clear_has_component_id();
  void set_has_pid();
  void clear_has_pid();
  void set_has_thread_id();
  void clear_has_thread_id();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr name_hash_;
  ::google::protobuf::internal::ArenaStringPtr hostid_;
  ::google::protobuf::internal::ArenaStringPtr composition_id_;
  ::google::protobuf::internal::ArenaStringPtr component_id_;
  ::google::protobuf::internal::ArenaStringPtr thread_id_;
  ::google::protobuf::int32 pid_;
  friend struct ::protobuf_runtime_5finfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// runtime_list_info_t

// required bytes id = 1 [default = ""];
inline bool runtime_list_info_t::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void runtime_list_info_t::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void runtime_list_info_t::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void runtime_list_info_t::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& runtime_list_info_t::id() const {
  // @@protoc_insertion_point(field_get:runtime_list_info_t.id)
  return id_.GetNoArena();
}
inline void runtime_list_info_t::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:runtime_list_info_t.id)
}
#if LANG_CXX11
inline void runtime_list_info_t::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:runtime_list_info_t.id)
}
#endif
inline void runtime_list_info_t::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:runtime_list_info_t.id)
}
inline void runtime_list_info_t::set_id(const void* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:runtime_list_info_t.id)
}
inline ::std::string* runtime_list_info_t::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:runtime_list_info_t.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* runtime_list_info_t::release_id() {
  // @@protoc_insertion_point(field_release:runtime_list_info_t.id)
  if (!has_id()) {
    return NULL;
  }
  clear_has_id();
  return id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void runtime_list_info_t::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:runtime_list_info_t.id)
}

// required bytes name_hash = 2 [default = ""];
inline bool runtime_list_info_t::has_name_hash() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void runtime_list_info_t::set_has_name_hash() {
  _has_bits_[0] |= 0x00000002u;
}
inline void runtime_list_info_t::clear_has_name_hash() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void runtime_list_info_t::clear_name_hash() {
  name_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name_hash();
}
inline const ::std::string& runtime_list_info_t::name_hash() const {
  // @@protoc_insertion_point(field_get:runtime_list_info_t.name_hash)
  return name_hash_.GetNoArena();
}
inline void runtime_list_info_t::set_name_hash(const ::std::string& value) {
  set_has_name_hash();
  name_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:runtime_list_info_t.name_hash)
}
#if LANG_CXX11
inline void runtime_list_info_t::set_name_hash(::std::string&& value) {
  set_has_name_hash();
  name_hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:runtime_list_info_t.name_hash)
}
#endif
inline void runtime_list_info_t::set_name_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name_hash();
  name_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:runtime_list_info_t.name_hash)
}
inline void runtime_list_info_t::set_name_hash(const void* value, size_t size) {
  set_has_name_hash();
  name_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:runtime_list_info_t.name_hash)
}
inline ::std::string* runtime_list_info_t::mutable_name_hash() {
  set_has_name_hash();
  // @@protoc_insertion_point(field_mutable:runtime_list_info_t.name_hash)
  return name_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* runtime_list_info_t::release_name_hash() {
  // @@protoc_insertion_point(field_release:runtime_list_info_t.name_hash)
  if (!has_name_hash()) {
    return NULL;
  }
  clear_has_name_hash();
  return name_hash_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void runtime_list_info_t::set_allocated_name_hash(::std::string* name_hash) {
  if (name_hash != NULL) {
    set_has_name_hash();
  } else {
    clear_has_name_hash();
  }
  name_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name_hash);
  // @@protoc_insertion_point(field_set_allocated:runtime_list_info_t.name_hash)
}

// required bytes hostid = 3 [default = ""];
inline bool runtime_list_info_t::has_hostid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void runtime_list_info_t::set_has_hostid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void runtime_list_info_t::clear_has_hostid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void runtime_list_info_t::clear_hostid() {
  hostid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_hostid();
}
inline const ::std::string& runtime_list_info_t::hostid() const {
  // @@protoc_insertion_point(field_get:runtime_list_info_t.hostid)
  return hostid_.GetNoArena();
}
inline void runtime_list_info_t::set_hostid(const ::std::string& value) {
  set_has_hostid();
  hostid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:runtime_list_info_t.hostid)
}
#if LANG_CXX11
inline void runtime_list_info_t::set_hostid(::std::string&& value) {
  set_has_hostid();
  hostid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:runtime_list_info_t.hostid)
}
#endif
inline void runtime_list_info_t::set_hostid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_hostid();
  hostid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:runtime_list_info_t.hostid)
}
inline void runtime_list_info_t::set_hostid(const void* value, size_t size) {
  set_has_hostid();
  hostid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:runtime_list_info_t.hostid)
}
inline ::std::string* runtime_list_info_t::mutable_hostid() {
  set_has_hostid();
  // @@protoc_insertion_point(field_mutable:runtime_list_info_t.hostid)
  return hostid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* runtime_list_info_t::release_hostid() {
  // @@protoc_insertion_point(field_release:runtime_list_info_t.hostid)
  if (!has_hostid()) {
    return NULL;
  }
  clear_has_hostid();
  return hostid_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void runtime_list_info_t::set_allocated_hostid(::std::string* hostid) {
  if (hostid != NULL) {
    set_has_hostid();
  } else {
    clear_has_hostid();
  }
  hostid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostid);
  // @@protoc_insertion_point(field_set_allocated:runtime_list_info_t.hostid)
}

// required bytes composition_id = 4 [default = ""];
inline bool runtime_list_info_t::has_composition_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void runtime_list_info_t::set_has_composition_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void runtime_list_info_t::clear_has_composition_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void runtime_list_info_t::clear_composition_id() {
  composition_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_composition_id();
}
inline const ::std::string& runtime_list_info_t::composition_id() const {
  // @@protoc_insertion_point(field_get:runtime_list_info_t.composition_id)
  return composition_id_.GetNoArena();
}
inline void runtime_list_info_t::set_composition_id(const ::std::string& value) {
  set_has_composition_id();
  composition_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:runtime_list_info_t.composition_id)
}
#if LANG_CXX11
inline void runtime_list_info_t::set_composition_id(::std::string&& value) {
  set_has_composition_id();
  composition_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:runtime_list_info_t.composition_id)
}
#endif
inline void runtime_list_info_t::set_composition_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_composition_id();
  composition_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:runtime_list_info_t.composition_id)
}
inline void runtime_list_info_t::set_composition_id(const void* value, size_t size) {
  set_has_composition_id();
  composition_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:runtime_list_info_t.composition_id)
}
inline ::std::string* runtime_list_info_t::mutable_composition_id() {
  set_has_composition_id();
  // @@protoc_insertion_point(field_mutable:runtime_list_info_t.composition_id)
  return composition_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* runtime_list_info_t::release_composition_id() {
  // @@protoc_insertion_point(field_release:runtime_list_info_t.composition_id)
  if (!has_composition_id()) {
    return NULL;
  }
  clear_has_composition_id();
  return composition_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void runtime_list_info_t::set_allocated_composition_id(::std::string* composition_id) {
  if (composition_id != NULL) {
    set_has_composition_id();
  } else {
    clear_has_composition_id();
  }
  composition_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), composition_id);
  // @@protoc_insertion_point(field_set_allocated:runtime_list_info_t.composition_id)
}

// required bytes component_id = 5 [default = ""];
inline bool runtime_list_info_t::has_component_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void runtime_list_info_t::set_has_component_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void runtime_list_info_t::clear_has_component_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void runtime_list_info_t::clear_component_id() {
  component_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_component_id();
}
inline const ::std::string& runtime_list_info_t::component_id() const {
  // @@protoc_insertion_point(field_get:runtime_list_info_t.component_id)
  return component_id_.GetNoArena();
}
inline void runtime_list_info_t::set_component_id(const ::std::string& value) {
  set_has_component_id();
  component_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:runtime_list_info_t.component_id)
}
#if LANG_CXX11
inline void runtime_list_info_t::set_component_id(::std::string&& value) {
  set_has_component_id();
  component_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:runtime_list_info_t.component_id)
}
#endif
inline void runtime_list_info_t::set_component_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_component_id();
  component_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:runtime_list_info_t.component_id)
}
inline void runtime_list_info_t::set_component_id(const void* value, size_t size) {
  set_has_component_id();
  component_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:runtime_list_info_t.component_id)
}
inline ::std::string* runtime_list_info_t::mutable_component_id() {
  set_has_component_id();
  // @@protoc_insertion_point(field_mutable:runtime_list_info_t.component_id)
  return component_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* runtime_list_info_t::release_component_id() {
  // @@protoc_insertion_point(field_release:runtime_list_info_t.component_id)
  if (!has_component_id()) {
    return NULL;
  }
  clear_has_component_id();
  return component_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void runtime_list_info_t::set_allocated_component_id(::std::string* component_id) {
  if (component_id != NULL) {
    set_has_component_id();
  } else {
    clear_has_component_id();
  }
  component_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), component_id);
  // @@protoc_insertion_point(field_set_allocated:runtime_list_info_t.component_id)
}

// required int32 pid = 6 [default = 0];
inline bool runtime_list_info_t::has_pid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void runtime_list_info_t::set_has_pid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void runtime_list_info_t::clear_has_pid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void runtime_list_info_t::clear_pid() {
  pid_ = 0;
  clear_has_pid();
}
inline ::google::protobuf::int32 runtime_list_info_t::pid() const {
  // @@protoc_insertion_point(field_get:runtime_list_info_t.pid)
  return pid_;
}
inline void runtime_list_info_t::set_pid(::google::protobuf::int32 value) {
  set_has_pid();
  pid_ = value;
  // @@protoc_insertion_point(field_set:runtime_list_info_t.pid)
}

// required bytes thread_id = 7 [default = ""];
inline bool runtime_list_info_t::has_thread_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void runtime_list_info_t::set_has_thread_id() {
  _has_bits_[0] |= 0x00000020u;
}
inline void runtime_list_info_t::clear_has_thread_id() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void runtime_list_info_t::clear_thread_id() {
  thread_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_thread_id();
}
inline const ::std::string& runtime_list_info_t::thread_id() const {
  // @@protoc_insertion_point(field_get:runtime_list_info_t.thread_id)
  return thread_id_.GetNoArena();
}
inline void runtime_list_info_t::set_thread_id(const ::std::string& value) {
  set_has_thread_id();
  thread_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:runtime_list_info_t.thread_id)
}
#if LANG_CXX11
inline void runtime_list_info_t::set_thread_id(::std::string&& value) {
  set_has_thread_id();
  thread_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:runtime_list_info_t.thread_id)
}
#endif
inline void runtime_list_info_t::set_thread_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_thread_id();
  thread_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:runtime_list_info_t.thread_id)
}
inline void runtime_list_info_t::set_thread_id(const void* value, size_t size) {
  set_has_thread_id();
  thread_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:runtime_list_info_t.thread_id)
}
inline ::std::string* runtime_list_info_t::mutable_thread_id() {
  set_has_thread_id();
  // @@protoc_insertion_point(field_mutable:runtime_list_info_t.thread_id)
  return thread_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* runtime_list_info_t::release_thread_id() {
  // @@protoc_insertion_point(field_release:runtime_list_info_t.thread_id)
  if (!has_thread_id()) {
    return NULL;
  }
  clear_has_thread_id();
  return thread_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void runtime_list_info_t::set_allocated_thread_id(::std::string* thread_id) {
  if (thread_id != NULL) {
    set_has_thread_id();
  } else {
    clear_has_thread_id();
  }
  thread_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), thread_id);
  // @@protoc_insertion_point(field_set_allocated:runtime_list_info_t.thread_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_runtime_5finfo_2eproto
